// Generate the page-side annotator the app injects into every page it shows.
//
// The annotator already exists: `extension/content.js` in the browser-annotate plugin is
// 1100 lines of element picker, computed-style reader, selector builder, inspect panel and
// comment box, and it was written to run inside the page it inspects. It reaches its
// surroundings through exactly five calls to `chrome.runtime`, so the honest way to reuse it
// here is to answer those five calls rather than to write a second picker that will drift
// from the first.
//
// The result is one preload with no `chrome.*` left in it. Being a preload is the point: it
// runs before any page script, so a page that replaces `console` or swallows its own events
// cannot take away the capture the annotation depends on.
//
// Usage: node scripts/build-overlay.mjs

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const app = join(here, '..')
const source = join(app, '..', 'extension', 'content.js')
const target = join(app, 'annotate-overlay.js')

const content = readFileSync(source, 'utf8')

// A guard rather than a transform. If the picker grows a sixth chrome call, the generated
// file would silently lose a feature — and a missing feature in an element picker looks
// exactly like a page that does not respond.
const provided = [
  "sendMessage({ type: 'requestDone', entry })",
  "sendMessage({ type: 'modeChanged', mode: next })",
  "sendMessage({ type: 'annotation', annotation: record })",
  "case 'context': {",
  'onMessage.addListener',
]
const allowed = new Set(['chrome.runtime', 'chrome.runtime.sendMessage', 'chrome.runtime.onMessage', 'chrome.runtime.onMessage.addListener'])
const unexpected = [...content.matchAll(/chrome\.[a-zA-Z.]+/g)]
  .map(match => match[0])
  .filter(name => !allowed.has(name))
const missing = provided.filter(fragment => !content.includes(fragment))
if (unexpected.length > 0 || missing.length > 0) {
  console.error('the picker no longer matches the shim below:')
  for (const name of new Set(unexpected)) console.error(`  unexpected: ${name}`)
  for (const fragment of missing) console.error(`  not found: ${fragment}`)
  process.exit(1)
}

const header = `// GENERATED by scripts/build-overlay.mjs — do not edit.
//
// The browser-annotate element picker, running inside the page it inspects, with the five
// \\\`chrome.runtime\\\` calls it makes answered by this app instead of by an extension.

/** Set by the shim below; starts the picker when there is a document to start it against. */
let kickoff = () => undefined

;(() => {
  const { contextBridge, ipcRenderer } = require('electron')

  // One place that answers both the real picker and this app's own calls, so a page cannot
  // tell the two apart and neither can drift from the other.
  const listeners = []
  const deliver = message => {
    for (const listener of listeners) {
      try {
        listener(message, { id: 'app' }, () => undefined)
      } catch {
        // One bad listener must not stop the others; the human is mid-annotation.
      }
    }
  }
  // Do NOT use ipcRenderer.sendToHost here. It belongs to a webview guest, and a
  // WebContentsView drops it silently: the message arrives nowhere and reports no error,
  // which is indistinguishable from a picker that simply has nothing to say. This cost an
  // afternoon. ipcRenderer.send reaches the app on the view's own ipc-message event.
  const send = message => {
    try {
      ipcRenderer.send('annotate', message)
    } catch {
      // A message that cannot be delivered must never break the picker.
    }
  }

  // The picker's own file expects to be an extension's content script. It is handed the only
  // part of that world it uses: a one-way sendMessage and a subscription.
  const runtime = { sendMessage: send, onMessage: { addListener: listener => listeners.push(listener) }, getURL: path => path }
  try {
    Object.defineProperty(globalThis, 'chrome', { value: { runtime }, configurable: true })
  } catch {
    globalThis.chrome = { runtime }
  }

  ipcRenderer.on('annotate-command', (_event, message) => deliver(message))

  // Handed to the code below, which starts the picker once there is a document for it to
  // attach to. The picker itself must not be started from in here: it is declared after this
  // block, and calling it from inside would reach it before it exists.
  kickoff = () => {
    try {
      startPicker()
      send({ type: '__installed', ok: true })
    } catch (error) {
      // Silence here is the worst possible outcome: an element picker that failed to install
      // looks exactly like a page that ignores clicks, and that is a bug report nobody can act
      // on. The failure is reported with its stack so the app can say what actually broke.
      send({ type: '__installed', ok: false, error: String((error && error.stack) || error) })
    }
  }

  // A request from the app, answered by the picker's own listener. The reply is matched to
  // the request by id, because a request that is answered by whichever reply arrives next is
  // a request that will one day describe the wrong element.
  ipcRenderer.on('annotate-request', (_event, request) => {
    const respond = value => send({ type: '__reply', id: request.id, value })
    for (const listener of listeners) {
      try {
        if (listener(request.message, { id: 'app' }, respond) !== false) return
      } catch (error) {
        respond({ ok: false, error: String(error && error.message) })
        return
      }
    }
    respond({ ok: false, error: 'nothing in this page answers that request' })
  })

  // The app's own handle on the picker, for driving it from a toolbar button or from the
  // agent's tools. It is the same surface either way.
  contextBridge.exposeInMainWorld('__annotate', {
    send,
    onCommand: listener => {
      listeners.push(listener)
      return () => {
        const index = listeners.indexOf(listener)
        if (index !== -1) listeners.splice(index, 1)
      }
    },
  })
})();

`

// Order matters and is the whole reason this is assembled rather than concatenated:
//   1. the picker, as a function, so it exists before anything can call it
//   2. the shim, which registers the channels the picker answers on
//   3. the kickoff, which is the first moment both are true
const picker = `const startPicker = () => {\n${content}\n}\n`
const tail = `
// The picker is a content script written to run at document_start, where Chromium guarantees a
// documentElement already exists. A preload runs earlier still, with no document at all, and an
// element cannot be created against one. So it starts at the first moment there is a document,
// and it is never retried: whatever it does on the way up, it does once.
if (document.documentElement !== null) kickoff()
else document.addEventListener('DOMContentLoaded', kickoff, { once: true })
`
writeFileSync(target, `${picker}${header}${tail}`)
console.log(`wrote ${target}`)
console.log(`  ${header.split('\n').length} lines of shim, ${content.split('\n').length} lines of picker`)
console.log(`  chrome.* remaining in the output: ${(header + content).split('chrome.runtime').length - 1} references, all to the shimmed object`)
